from __future__ import annotations

from dataclasses import dataclass
from datetime import date
from pathlib import Path


def esc(s: str) -> str:
    return s.replace('\\', '\\\\').replace('(', '\\(').replace(')', '\\)')


@dataclass
class Report:
    title: str
    period: str
    sections: list[tuple[str, list[str]]]
    footer: str


def build_stream(r: Report) -> bytes:
    lines: list[str] = []

    # Plain white page
    lines.append("1 1 1 rg")
    lines.append("0 0 595 842 re f")

    t: list[str] = []
    t.append("BT")

    # Title
    t.append("0 0 0 rg")
    t.append("/F2 18 Tf")
    t.append("1 0 0 1 50 800 Tm")
    t.append(f"({esc(r.title)}) Tj")

    # Period
    t.append("/F1 11 Tf")
    t.append("1 0 0 1 50 782 Tm")
    t.append(f"({esc(r.period)}) Tj")

    y = 752
    for heading, bullets in r.sections:
        t.append("/F2 12 Tf")
        t.append(f"1 0 0 1 50 {y} Tm")
        t.append(f"({esc(heading)}) Tj")
        y -= 18

        t.append("/F1 11 Tf")
        for b in bullets:
            # soft wrap by manual shortening if needed
            line = "• " + b
            if len(line) > 110:
                line = line[:107] + "…"
            t.append(f"1 0 0 1 56 {y} Tm")
            t.append(f"({esc(line)}) Tj")
            y -= 16
        y -= 10

        if y < 80:
            break

    # Footer
    t.append("/F1 9 Tf")
    t.append("1 0 0 1 50 40 Tm")
    t.append(f"({esc(r.footer)}) Tj")

    t.append("ET")

    lines.extend(t)
    return "\n".join(lines).encode("latin-1", errors="replace")


def generate_pdf(path: Path, r: Report):
    header = b"%PDF-1.4\n"
    objs: list[str] = []

    objs.append("1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n")
    objs.append("2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n")
    objs.append(
        "3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] "
        "/Resources << /Font << /F1 4 0 R /F2 5 0 R >> >> /Contents 6 0 R >>\nendobj\n"
    )
    objs.append("4 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj\n")
    objs.append("5 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>\nendobj\n")

    stream = build_stream(r)
    objs.append(
        f"6 0 obj\n<< /Length {len(stream)} >>\nstream\n"
        + stream.decode("latin-1")
        + "\nendstream\nendobj\n"
    )

    body = ""
    offsets = [0]
    cur = len(header)
    for o in objs:
        offsets.append(cur)
        cur += len(o.encode("latin-1"))
        body += o

    xref_start = cur
    xref = [f"xref\n0 {len(objs)+1}\n", "0000000000 65535 f \n"]
    for off in offsets[1:]:
        xref.append(f"{off:010d} 00000 n \n")

    trailer = (
        f"trailer\n<< /Size {len(objs)+1} /Root 1 0 R >>\nstartxref\n{xref_start}\n%%EOF\n"
    )

    path.parent.mkdir(parents=True, exist_ok=True)
    pdf = header + body.encode("latin-1") + "".join(xref).encode("latin-1") + trailer.encode("latin-1")
    path.write_bytes(pdf)


if __name__ == "__main__":
    today = date.today().isoformat()
    r = Report(
        title="AIP — Month-to-date report (plain)",
        period=f"Period: 2026-02-01 → {today}",
        sections=[
            (
                "Highlights",
                [
                    "Core messaging + channel wiring stabilised (DM routing live)",
                    "Group comms path identified; remaining work is allowlisting + permissions",
                    "Reporting pipeline: plain PDF output available on demand",
                ],
            ),
            (
                "KPI snapshot (MTD)",
                [
                    "Indexed URLs: TBD",
                    "Top-10 terms: TBD",
                    "Lead volume: TBD",
                ],
            ),
            (
                "Risks / blockers",
                [
                    "Telegram bot tokens were posted in chat earlier — ensure they are revoked/rotated",
                    "Group responses depend on group permissions + allowlist policy",
                ],
            ),
            (
                "Next actions (next 14 days)",
                [
                    "Confirm KPI sources (GSC/GA4/rank tracker) and lock the metric set",
                    "Add Picard + Riker to target groups; capture group chat IDs; enable allowlist entries",
                    "Automate MTD report generation + send as PDF on schedule",
                ],
            ),
        ],
        footer=f"Generated by OpenClaw • {today}",
    )

    generate_pdf(Path(f"reports/aip-mtd-plain-{today}.pdf"), r)
